name: Local pip install

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            needs_cuda: true
          - os: windows-2022
            needs_cuda: false
          - os: macos-13
            needs_cuda: false
          - os: macos-14
            needs_cuda: false
      max-parallel: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v2.0.0

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.26.0"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 055721089e8037d4d617250814d11f881e557549

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use a compatible version

      - name: Install CUDA (Linux Only)
        if: matrix.needs_cuda == 'true' && runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.17
        id: cuda-toolkit
        with:
          cuda: '12.4.0'
          sub-packages: '["nvcc"]'
          method: 'network'

      - name: Add CUDA to CUDA_PATH environment variable (Linux Only)
        if: matrix.needs_cuda == 'true' && runner.os == 'Linux'
        run: |
          echo "CUDA_PATH=${{ steps.cuda-toolkit.outputs.cuda-path }}" >> $GITHUB_ENV
          echo "CUDA_PATH environment variable set to ${{ steps.cuda-toolkit.outputs.cuda-path }}"

      - name: Install doctest
        run: sudo apt-get install doctest-dev || true  # To avoid CMake error

      - name: Build and install PBAT Python bindings
        run: |
          pip install . --config-settings=cmake.args="--preset=pip" --config-settings=build.tool-args="${{ steps.cpu-cores.outputs.cores }}" -v

      - name: Run PBAT Python toolkit and inspect modules
        run: |
          python -c "import pbatoolkit as pbat"
