name: build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: windows-2022
            build_tool_args: /p:CL_MPCount=4
          - os: macos-13
          - os: macos-14
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.26.0"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 055721089e8037d4d617250814d11f881e557549

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2.0.0
        id: cpu-cores
        continue-on-error: true

      - name: Set build tool arguments for Unix systems
        if: ${{ runner.os != 'Windows' }}
        run: |
          if [ -z "${{ steps.cpu-cores.outputs.cores }}" ]; then
            echo "build_tool_args=-j4" >> $GITHUB_ENV
          else
            echo "build_tool_args=-j${{ steps.cpu-cores.outputs.cores }}" >> $GITHUB_ENV
          fi
        id: set-build-args

      - name: Build and install PBAT Python bindings (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          pip install . --config-settings=cmake.args="--preset=pip" --config-settings=build.tool-args="${{ env.build_tool_args }}" -v

      - name: Build and install PBAT Python bindings (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          pip install . --config-settings=cmake.args="--preset=pip" --config-settings=build.tool-args="${{ matrix.build_tool_args }}" -v

      - name: Run PBAT Python toolkit and inspect modules
        run: |
          python -c "import pbatoolkit as pbat"
